package:
  name: cloudmesh-sys
  version: "{{ load_setup_py_data().version }}"

source:
  git_url: https://github.com/cloudmesh/cloudmesh-sys.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pip
    - cloudmesh-common

  run:
    - cloudmesh-common
    - wheel
    - twine
