package:
  name: cloudmesh
  version: 4.0

source:
  git_rev:
  git_url:

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
  license:
  license_file: