package:
  name: cloudmesh-openapi
  version: 4.0.21

source:
  git_url: https://github.com/cloudmesh/cloudmesh-openapi.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pip
    - cloudmesh-common
    - cloudmesh-cmd5

  run:
    - psutil
    - pygments
    - cloudmesh-common
    - cloudmesh-cmd5
