package:
  name: cloudmesh-inventory
  version: 4.0.21

source:
  git_url: https://github.com/cloudmesh/cloudmesh-cmd5.git

build:
  number: 0

requirements:
  build:
    - python
    - pyyaml
    - docopt
    - requests
    - cloudmesh-common
    - cloudmesh-cmd5


  run:
    - pyyaml
    - docopt
    - requests
    - cloudmesh-common
    - cloudmesh-cmd5



