package:
  name: cloudmesh-common
  version: 4.0.21

source:
  git_url: https://github.com/cloudmesh/cloudmesh-common.git

build:
  number: 0

requirements:
  build:
    - python
    - six
    - future
    - python-hostlist
    - simplejson
    - oyaml
    - colorama
    - psutil

  run:
    - python
    - six
    - future
    - simplejson
    - colorama
    - psutil
